//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class rin
    {
        public int ID { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<decimal> TamañoRin { get; set; }
        public Nullable<decimal> TamañoLlanta { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> FenchEnt { get; set; }
        public Nullable<System.DateTime> FechSal { get; set; }
        public Nullable<int> ClienteID { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
